# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle to QA

on:
  push:
    branches: [ 'releases/**' ]
  pull_request:
    branches: [ 'releases/**' ]

jobs:
  build:

    runs-on: [self-hosted, linux, x64, qa]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Sets up JDK 8 Caching gradle packages dependencies
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
        
    # Make sure gradlew is executable
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Execute Gradle Build
    - name: Build with Gradle
      run: ./gradlew build
      
    # Upload a Deployment Artifacts
    - name: Upload a Deployment Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: target/*
